### ISSUE TITLE
Appreciation and questions

### ISSUE THREAD

**Issue by lemerv** [TheHesster/radarr-cf-search#1]
Hey TheHesster, thanks so much for sharing this. Really appreciate it. When I get a chance I’ll dive it. 

As I mentioned I’m a novice with python. If you don’t mind I’ll use this issue thread to ask some questions if that’s ok?

Thanks again 👍

**Comment by TheHesster** [comment]
Ya sure no worries. I bet I'm not much more advanced than you hahahhahah

**Comment by TheHesster** [comment]
There's really no logging or output of any sort from this. Try it out on a cron job for every 5 mins or so and watch in radarr to see if you see the search happening in the bottom right corner or in the logs.

It's working for me.

**Comment by lemerv** [comment]
I bet you are haha! It's great and simple starting point for me. Will keep you updated

**Comment by lemerv** [comment]
Of interest, where are you running this? My arrs setup is in docker on a Synology. That's where I'll try and get this going.

**Comment by TheHesster** [comment]
Ya all my stuff runs on docker on a proxmox cluster.
So I just have a separate LXC container doing this for me.

**Comment by TheHesster** [comment]
Just quickly looking at the python docker image I might be able to quickly turn this into a docker image that can be pulled and run instead of the way it is now.

**Comment by sleighton** [comment]
Jumping in here. I did that about an hour ago. Here's the Dockerfile.

```
FROM python:3.9-slim

WORKDIR /app

# Install system dependencies including net-tools for health checks
RUN apt-get update && apt-get install -y --no-install-recommends \
    net-tools \
    && rm -rf /var/lib/apt/lists/*

# Install required packages from the root requirements file
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . /app/

# Create necessary directories
RUN mkdir -p /config/ /config/logs
RUN chmod -R 755 /config

# Set environment variables
ENV PYTHONPATH=/app

# Run the main application using the new entry point
CMD ["python3", "app.py"]
```

And a docker compose file. 

```
services:
  radarr-cf-search:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: radarr-cf-search
    volumes:
      - radarr-cf-search-config:/config
    environment:
      - RADARR_API_KEY=<<radarr api key here>>
      - RADARR_URL=http://192.168.86.131:7878
      - NUM_MOVIES_TO_UPGRADE=5
      - TZ=America/Los_Angeles

volumes:
  radarr-cf-search-config:
    name: radarr-cf-search-config
```

I was thinking of adding logging hence the extra stuff and using the ofelia-scheduler to schedule it nightly.

**Comment by lemerv** [comment]
Ok cool. Yeah if you want to have ago that would be great. Either way I'll have a play around with it.

**Comment by sleighton** [comment]
The docker compose for the ofelia-scheduler 

```
services:
  ofelia-scheduler:
    image: mcuadros/ofelia
    container_name: ofelia-scheduler
    command: daemon --docker
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=America/Los_Angeles
    labels:
      ofelia.smtp-host: "192.168.86.55"
      ofelia.smtp-port: "25"
      ofelia.mail-only-on-error: 'true'
      ofelia.email-from: '<your email>@gmail.com'
      ofelia.email-to: '<your email>@gmail.com'
      ofelia.job-run.radarr-cf-search.schedule: '@every 24h'    <-- or '@every 5m' if you wish
      ofelia.job-run.radarr-cf-search.container: 'radarr-cf-search'
```
